# Generated by Django 3.2.3 on 2021-05-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonModel',
            new_name='Person',
        ),
    ]
